version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secure@password"
      MYSQL_DATABASE: "voting"
      MYSQL_USER: "voting_user"
      MYSQL_PASSWORD: "voting_password"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  voting-service:
    image: mathiasbald/voting
    entrypoint: "./wait-for-it.sh -t 0 mysql:3306 -- java -jar app.jar"
    environment:
      DB_URL: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "voting"
      DB_USERNAME: "voting_user"
      DB_PASSWORD: "voting_password"
    ports:
      - "8080:8080"


volumes:
  mysql-data:
    external: false