spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_DATABASE:voting}
    username: ${DB_USERNAME:voting_user}
    password: ${DB_PASSWORD:voting_password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    schemas: ${DB_DATABASE:voting}
    user:  ${DB_USERNAME:voting_user}
    password: ${DB_PASSWORD:voting_password}


server:
  servlet:
    context-path: /voting